# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFWymROWaE-BL1scJLgNb4Q-qDWZDFyq
"""

def listar_productos(p1, p2, p3):
    print("\n--- Carrito de Compras ---")
    carrito = [p1, p2, p3]
    for i, producto in enumerate(carrito, 1):
        print(f"{i}. {producto}")
    return len(carrito)

def calcular_descuento(precio_base, edad_del_cliente, es_miembro):
    descuento = 0
    if edad_del_cliente < 18:
        descuento += 10

    if es_miembro == True:
        descuento += 15

    precio_final = precio_base - (precio_base * (descuento / 100))
    return precio_final

def hacer_factura(nombre, total, ubicacion):
    impuesto = 0.21 # Ejemplo: 21% de IVA
    total_con_impuesto = total * (1 + impuesto)

    print("--- FACTURA ----------")
    print(f"Cliente: {nombre}")
    print(f"Región de envío: {ubicacion}")
    print(f"Subtotal con descuentos: ${total:.2f}")
    print(f"Total a pagar (con IVA): ${total_con_impuesto:.2f}")
    print("----------------------")

usuario = "Pepe"
item1, item2, item3 = "Postal 2 redux CD", "Silent Hill F CD", "Almohada Nekopara Vanilla 30x20"
precio_acumulado = 120000000.0

listar_productos(item1, item2, item3)
precio_con_descuento = calcular_descuento(precio_acumulado, 2, True)
hacer_factura(usuario, precio_con_descuento, "Jujuy")